site_name: Lập trình Python
site_description: Programming with Python
site_author: Hung Nguyen

repo_url: https://github.com/nd-hung/python-programming
edit_uri: tree/main/docs

nav:
    - Các chủ đề:
      - Giới thiệu ngôn ngữ lập trình Python: topics\overview\README.md
      - Python cơ bản: topics\python-basic
      - Python nâng cao: topics\advanced-python
      - Lập trình hướng đối tượng với Python: topics\python-oop
      - Một số thư viện Python thông dụng: topics\
      - Tạo ứng dụng GUI: topics\gui
      - Phát triển ứng dụng web với Python: topics\
      - Xây dựng, triển khai ứng dụng AI: topics\
      - Bài thực hành: labs\README.md
    - About: author\about.md 

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
        - content.action.view
 
extra_css:
  - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - def_list
    - tables
    - admonition
