site_name: Lập trình Python
site_description: Programming with Python
site_author: Hung Nguyen

repo_url: https://github.com/nd-hung/python
edit_uri: tree/main/docs

nav:
    - Các chủ đề:
      - Tổng quan: topics\overview\README.md
      - Python cơ bản: topics\dotnet-and-csharp\README.md
      - Lập trình hướng đối tượng với Python: topics\classes-and-objects\README.md
      - Một số xử lý cơ bản & thư viện thông dụng: topics\inheritance\README.md
      - Phát triển ứng dụng với Python: topics\polymorphism\README.md
      - Xây dựng giải pháp học máy, khoa học dữ liệu: topics\filehandling\README.md
      - Bài thực hành: labs\README.md
    - Giảng viên: author\about.md 

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
        - content.action.view
 
extra_css:
  - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - def_list
    - tables
